version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend-next"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/ai/egyptian-voice-medical-analyzer"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mobile/MedAI"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/frontend-next/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/backend/docker"
    schedule:
      interval: "daily"
