frontend:
  - 'frontend/**'
backend:
  - 'backend/**'
mobile:
  - 'mobile/**'
docs:
  - '**/*.md'
docker:
  - 'docker-compose/**'
  - '**/docker/**'
makefile:
  - 'Makefile'
github-actions:
  - '.github/**'
