[tool.poetry]
name = "medai"
version = "0.1.0"
description = ""
authors = ["Mostafa Atef <mostafaatefsaad705@gmail.com>","Ahmed Gouda <ahmedmosad405@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django-ninja = "^1.4.3"
psycopg2-binary = "^2.9.11"
python-decouple = "^3.8"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
