import os
import re
import json
import shutil
import time
from fastapi import FastAPI, UploadFile, File, HTTPException, Security, status
from fastapi.security import APIKeyHeader
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

# Import your custom engines
from models.stt_engine import EgyptianSTT
from models.nlu_engine import MedicalAnalyzer

# --- 1. API Security Configuration ---
API_KEY_NAME = "X-MedAI-API-Key"
api_key_header = APIKeyHeader(name=API_KEY_NAME, auto_error=False)
MEDAI_SECRET_KEY = "super_secret_graduation_token_2026"

def validate_api_key(api_key: str = Security(api_key_header)):
    if api_key != MEDAI_SECRET_KEY:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unauthorized: Invalid API Key"
        )
    return api_key

# --- 2. Initialize FastAPI Application ---
app = FastAPI(
    title="MedAI Parallel Backend API",
    description="Optimized for 24GB VRAM (Always-Loaded Models) - Mansoura University 2026",
    version="2.0.0"
)

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class TextPayload(BaseModel):
    text: str

def extract_clean_json(raw_output: str):
    json_match = re.search(r'\{.*\}', raw_output, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group())
        except:
            return {"error": "Invalid JSON format generated by model", "raw": raw_output}
    return {"error": "No JSON block found in model output", "raw": raw_output}


# --- 3. Global Model Initialization (The 24GB VRAM Magic) ---
print("\n🚀 [STARTUP] Loading Whisper STT into VRAM permanently...")
stt_engine = EgyptianSTT()

print("🚀 [STARTUP] Loading Llama-3 Medical Brain into VRAM permanently...")
nlu_engine = MedicalAnalyzer()
print("✅ All models successfully pinned to GPU memory! Server is ready.")


# --- ENDPOINT 1: Full Pipeline (Audio -> Clinical JSON) ---
@app.post("/api/v1/pipeline")
async def full_voice_to_clinical_pipeline(
    audio_file: UploadFile = File(...),
    _: str = Security(validate_api_key)
):
    temp_path = f"temp_{audio_file.filename}"
    with open(temp_path, "wb") as buffer:
        shutil.copyfileobj(audio_file.file, buffer)

    try:
        print("\n⏱️  --- STARTING PROFILING ---")

        # 1. قياس وقت الـ STT (Whisper)
        start_stt = time.time()
        transcription = stt_engine.transcribe(temp_path)
        end_stt = time.time()
        stt_duration = end_stt - start_stt
        print(f"🔊 STT (Whisper) Took: {stt_duration:.2f} seconds")

        if transcription.startswith("Error:"):
            raise HTTPException(status_code=500, detail=f"STT Failed: {transcription}")

        # 2. قياس وقت الـ NLU (Llama-3)
        start_nlu = time.time()
        raw_nlu_output = nlu_engine.analyze(transcription)
        structured_json = extract_clean_json(raw_nlu_output)
        end_nlu = time.time()
        nlu_duration = end_nlu - start_nlu
        print(f"🧠 NLU (Llama-3) Took: {nlu_duration:.2f} seconds")

        print(f" Total Pipeline Execution Time: {stt_duration + nlu_duration:.2f} seconds")
        print("⏱️  --- END OF PROFILING ---\n")

        return {
            "status": "success",
            "transcription": transcription,
            "clinical_report": structured_json
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)


# --- ENDPOINT 2: STT Only (Audio -> Egyptian Arabic Text) ---
@app.post("/api/v1/stt")
async def speech_to_text_only(
    audio_file: UploadFile = File(...),
    _: str = Security(validate_api_key)  # Securing Endpoint
):
    temp_path = f"temp_{audio_file.filename}"
    with open(temp_path, "wb") as buffer:
        shutil.copyfileobj(audio_file.file, buffer)

    try:
        transcription = stt_engine.transcribe(temp_path)
        return {
            "status": "success",
            "transcription": transcription
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)


# --- ENDPOINT 3: NLU Only (Text -> Clinical JSON) ---
@app.post("/api/v1/analyze-text")
async def text_to_clinical_only(
    payload: TextPayload,
    _: str = Security(validate_api_key)  # Securing Endpoint
):
    if not payload.text.strip():
        raise HTTPException(status_code=400, detail="Input text cannot be empty.")

    try:
        raw_output = nlu_engine.analyze(payload.text)
        structured_json = extract_clean_json(raw_output)

        return {
            "status": "success",
            "clinical_report": structured_json
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    # تشغيل السيرفر على بورت 80
    uvicorn.run("app:app", host="0.0.0.0", port=80, reload=False)
