services:
  backend:
    container_name: prod-medai-backend
    image: medaigradprojrepo.azurecr.io/medai-prod-backend:latest
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.prod
    restart: always
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    container_name: prod-medai-frontend
    image: medaigradprojrepo.azurecr.io/medai-prod-frontend:latest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.frontend.prod
    restart: always

  redis:
    container_name: prod-medai-redis
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
