FROM node:26-alpine AS builder

SHELL ["/bin/sh", "-c", "-o", "pipefail"]

ENV APK_CACHE_DIR="/medai/.cache/apk-backend-builder" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    NPM_CACHE_DIR="/medai/.cache/npm" \
    PNPM_HOME="/pnpm"

ENV NPM_CONFIG_RETRY=5 \
    NPM_CONFIG_TIMEOUT=30000 \
    PATH="$PNPM_HOME:$PATH"

RUN mkdir -p ${APK_CACHE_DIR} \
    && ln -s ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}


RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk update && apk upgrade \
    && addgroup -S medai \
    && adduser -S -h /medai -G medai medai \
    && chown -R medai:medai /medai

RUN --mount=type=cache,target=${NPM_CACHE_DIR} \
    npm install -g pnpm@9 --cache ${NPM_CACHE_DIR}

WORKDIR /medai/

COPY --chmod=444 --chown=root:root package.json pnpm-lock.yaml ./
RUN --mount=type=cache,target=/pnpm/store,id=pnpm \
    pnpm install --frozen-lockfile

COPY src src
COPY tests tests
COPY tsconfig.json ./

FROM node:26-alpine
SHELL ["/bin/sh", "-c", "-o", "pipefail"]

ENV APK_CACHE_DIR="/medai/.cache/apk-backend" \
    APK_SYMLINK_DIR="/etc/apk/cache" \
    FORCE_COLOR=1 \
    NPM_CACHE_DIR="/medai/.cache/npm"

RUN mkdir -p ${APK_CACHE_DIR} \
    && ln -s ${APK_CACHE_DIR} ${APK_SYMLINK_DIR}

RUN --mount=type=cache,target=${APK_CACHE_DIR} \
    apk update && apk upgrade \
    && addgroup -S medai \
    && adduser -S -h /medai -G medai medai \
    && chown -R medai:medai /medai

RUN --mount=type=cache,target=${NPM_CACHE_DIR} \
    npm install -g pnpm@9 --cache ${NPM_CACHE_DIR}

COPY --from=builder --chown=root:root /medai/ /medai/

WORKDIR /medai/
USER medai
